updating the example
ipfs/js-ipfs pull request #3596
Opened 2021-03-19 11:15 UTC by MisterY

Applying all the magic from #3582,
updating the dependencies,
adding tips (address example) for working with a local node

2021-03-29 14:48 UTC, lidel commented
Blocked until https://github.com/ipfs/js-ipfs/issues/2945 is done :)

2021-05-26 12:48 UTC, vasco-santos requested changes
Thanks for the PR @MisterY  and apologies for a late review

I have two requests here:

- can you rebase this PR to fix the conflicts?
- can you update the Readme? The addresses in https://github.com/ipfs/js-ipfs/tree/master/examples/browser-ipns-publish#3-open-the-demo-in-a-browser-and-connect-to-the-go-node should be the websockets addrs as you added in the html file, not TCP as browsers do not speak tcp

2021-05-26 12:48 UTC, vasco-santos commented on examples/browser-ipns-publish/index.html
> +      -->
```suggestion
```

2021-05-26 12:48 UTC, vasco-santos commented on examples/browser-ipns-publish/index.html
> +        For connecting to a local go-ipfs node, you may need to use
```suggestion
        For connecting to a local go-ipfs node, you can check its listening address similar to:
```

2021-06-14 14:31 UTC, BigLep commented
@Gozala : are you able to check to see if this can be merged now?

2021-06-22 08:16 UTC, vasco-santos commented
@MisterY can you please rebase the PR with master as this seems to have a conflict now?

2021-06-22 09:09 UTC, MisterY commented
Updated!

2021-06-22 12:10 UTC, vasco-santos approved these changes
LGTM thanks @MisterY

2021-06-30 08:24 UTC, oliveriosousa commented
Hi @MisterY, 

Thanks for your improvements, I was having problems connecting using web sockets and this did the trick.

I just want to add one thing, it might be needed to change one line of code:

https://github.com/MisterY/js-ipfs/blob/c70422c07f67401980f10488cd2e8b765b2885b9/examples/browser-ipns-publish/index.js#L58-L73

From this,
`ipfsAPI = IpfsHttpClient(url)`

To:
`ipfsAPI = IpfsHttpClient.create(url)`

May be related to an update of `ipfs-http-client`

2021-07-19 14:38 UTC, achingbrain approved these changes
LGTM, just waiting on CI

2021-07-19 15:51 UTC, merged