feat: add multibaseName option for addAll
ipfs/js-ipfs pull request #3650
Opened 2021-04-28 13:19 UTC by chrisdukakis

Requires https://github.com/multiformats/js-cid/pull/144 & https://github.com/ipfs/js-ipfs-unixfs/pull/146

2021-04-28 14:22 UTC, achingbrain requested changes
Could you please add tests to `packages/interface-ipfs-core/src/add.js` and `packages/interface-ipfs-core/src/add-all.js` to prevent future regressions.

2021-04-28 14:22 UTC, achingbrain commented on packages/ipfs-core-types/src/root.d.ts
> +  multibaseName?: string
Please use a `BaseName` type from [multibase](https://www.npmjs.com/package/multibase) instead of a string.

2021-04-29 11:58 UTC, chrisdukakis commented
Hi, I notice that cli has a [cidBase option](https://github.com/ipfs/js-ipfs/blob/28ad9ad6e50abb89a366ecd6b5301e848f0e9962/packages/ipfs-cli/src/commands/add.js#L321) for formatting output. Should I pass it to `addAll` options?

2021-05-21 15:46 UTC, hugomrdias commented
we should either use the same name in the cli and api or just rely on cid version at least in this api

2021-05-24 14:14 UTC, BigLep commented
2021-05-24 next step: @hugomrdias and @achingbrain are going to discuss.

2021-05-25 00:12 UTC, lidel commented
Additional comment from triage: given that JS APIs return CID, I think https://github.com/multiformats/js-cid/pull/144  is enough.
One can choose multibase via `cid.toString(base=base2)` already, we need to think twice if we want to create a precedent of additng this parameter to  every command that returns CID.

2021-05-27 13:25 UTC, chrisdukakis commented
Hi @lidel, idea is to create self-describing cid, not to convert. So methods _creating_ cids may use `multibaseName`, while others which return existing cids don't have to.

2021-06-14 14:23 UTC, BigLep commented
2021-06-14: @lidel is going to respond here on how we should proceed?

2021-06-15 13:06 UTC, lidel commented
Thank you @chrisdukakis  for submitting this, it helped us to clarify our policy regarding CIDs.
We marinated on this during weekly triage and the decision is to close this pecific  PR without merging.

Rationale:
- `add` operations are  not the only ones that return a CID – if we accept this, then we would either have incosistent APIs, or had to complicate every API by adding the multibase parameter
- Creating  vs converting is a fuzzy topic: multibase matters only when CIDv1 is serialized to text, and one could use CID without ever doing that, so introducing a parameter that controls something  indirect like that, at different abstraciton layer, is somehow wasteful
-  CID object provides the ability to customize base encoding when serializing to text already (`CID.toString(base)`),  and `toV1().toString(base)` could be used to ensure arbitrary representation as CIDv1 without the need for changing all IPFS commands

2021-06-15 13:06 UTC, closed without merging