fix: reject requests when cors origin list is empty
ipfs/js-ipfs pull request #3674
Opened 2021-05-06 13:51 UTC by achingbrain

If CORS origin list is empty, Hapi throws an error as it considers
that to be invalid configuration.

We want to reject requests that send and origin or a referrer when
no allowed origins have been configured, so when these headers are
sent, reject the request if no allowed origins are present in the
config.

2021-05-06 16:35 UTC, vasco-santos requested changes

2021-05-06 16:35 UTC, vasco-santos commented on packages/ipfs-http-server/src/index.js
> + * @param {string} str
```suggestion
 * @param {string} [str]
```
it might be empty

2021-05-06 16:35 UTC, vasco-santos commented on packages/ipfs-http-server/src/index.js
> + * @param {string[]} allowedOrigins
```suggestion
 * @param {string[]} [allowedOrigins]
```
not required

2021-05-07 01:23 UTC, lidel approved these changes
I did not run this, but should do the trick of aligning with what we do in  go-ipfs.
Small nits below.

2021-05-07 10:31 UTC, vasco-santos approved these changes

2021-05-07 10:56 UTC, achingbrain commented on packages/ipfs-http-server/test/cors.js
> +    it('rejects requests when cors origin list is empty and origin is sent', async () => {
Done!

2021-05-07 11:00 UTC, merged